/* tslint:disable */
/* eslint-disable */
/**
 * DockerSpring POC
 * My API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { UniEngineer } from './UniEngineer';
import {
    UniEngineerFromJSON,
    UniEngineerFromJSONTyped,
    UniEngineerToJSON,
    UniEngineerToJSONTyped,
} from './UniEngineer';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageUniEngineer
 */
export interface PageUniEngineer {
    /**
     * 
     * @type {number}
     * @memberof PageUniEngineer
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUniEngineer
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageUniEngineer
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageUniEngineer
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageUniEngineer
     */
    size?: number;
    /**
     * 
     * @type {Array<UniEngineer>}
     * @memberof PageUniEngineer
     */
    content?: Array<UniEngineer>;
    /**
     * 
     * @type {number}
     * @memberof PageUniEngineer
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageUniEngineer
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageUniEngineer
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageUniEngineer
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageUniEngineer
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageUniEngineer interface.
 */
export function instanceOfPageUniEngineer(value: object): value is PageUniEngineer {
    return true;
}

export function PageUniEngineerFromJSON(json: any): PageUniEngineer {
    return PageUniEngineerFromJSONTyped(json, false);
}

export function PageUniEngineerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageUniEngineer {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UniEngineerFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageUniEngineerToJSON(json: any): PageUniEngineer {
    return PageUniEngineerToJSONTyped(json, false);
}

export function PageUniEngineerToJSONTyped(value?: PageUniEngineer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UniEngineerToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

