/* tslint:disable */
/* eslint-disable */
/**
 * DockerSpring POC
 * My API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { UniUserDTO } from './UniUserDTO';
import {
    UniUserDTOFromJSON,
    UniUserDTOFromJSONTyped,
    UniUserDTOToJSON,
    UniUserDTOToJSONTyped,
} from './UniUserDTO';

/**
 * 
 * @export
 * @interface PageUniUserDTO
 */
export interface PageUniUserDTO {
    /**
     * 
     * @type {number}
     * @memberof PageUniUserDTO
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUniUserDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageUniUserDTO
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageUniUserDTO
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageUniUserDTO
     */
    size?: number;
    /**
     * 
     * @type {Array<UniUserDTO>}
     * @memberof PageUniUserDTO
     */
    content?: Array<UniUserDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageUniUserDTO
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageUniUserDTO
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageUniUserDTO
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageUniUserDTO
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageUniUserDTO
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageUniUserDTO interface.
 */
export function instanceOfPageUniUserDTO(value: object): value is PageUniUserDTO {
    return true;
}

export function PageUniUserDTOFromJSON(json: any): PageUniUserDTO {
    return PageUniUserDTOFromJSONTyped(json, false);
}

export function PageUniUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageUniUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UniUserDTOFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageUniUserDTOToJSON(json: any): PageUniUserDTO {
    return PageUniUserDTOToJSONTyped(json, false);
}

export function PageUniUserDTOToJSONTyped(value?: PageUniUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UniUserDTOToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

