/* tslint:disable */
/* eslint-disable */
/**
 * DockerSpring POC
 * My API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UniEngineerDTO
 */
export interface UniEngineerDTO {
    /**
     * 
     * @type {number}
     * @memberof UniEngineerDTO
     */
    uniEngineerId?: number;
}

/**
 * Check if a given object implements the UniEngineerDTO interface.
 */
export function instanceOfUniEngineerDTO(value: object): value is UniEngineerDTO {
    return true;
}

export function UniEngineerDTOFromJSON(json: any): UniEngineerDTO {
    return UniEngineerDTOFromJSONTyped(json, false);
}

export function UniEngineerDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UniEngineerDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'uniEngineerId': json['uniEngineerId'] == null ? undefined : json['uniEngineerId'],
    };
}

export function UniEngineerDTOToJSON(json: any): UniEngineerDTO {
    return UniEngineerDTOToJSONTyped(json, false);
}

export function UniEngineerDTOToJSONTyped(value?: UniEngineerDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uniEngineerId': value['uniEngineerId'],
    };
}

