/* tslint:disable */
/* eslint-disable */
/**
 * DockerSpring POC
 * My API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * UniUserDTO
 * @export
 * @interface UniUserDTO
 */
export interface UniUserDTO {
    /**
     * The unique ID of the user
     * @type {string}
     * @memberof UniUserDTO
     */
    name?: string;
    /**
     * The email of the user
     * @type {string}
     * @memberof UniUserDTO
     */
    email?: string;
    /**
     * Role of the user
     * @type {string}
     * @memberof UniUserDTO
     */
    role?: UniUserDTORoleEnum;
}


/**
 * @export
 */
export const UniUserDTORoleEnum = {
    Engineer: 'ENGINEER',
    Sales: 'SALES',
    Business: 'BUSINESS'
} as const;
export type UniUserDTORoleEnum = typeof UniUserDTORoleEnum[keyof typeof UniUserDTORoleEnum];


/**
 * Check if a given object implements the UniUserDTO interface.
 */
export function instanceOfUniUserDTO(value: object): value is UniUserDTO {
    return true;
}

export function UniUserDTOFromJSON(json: any): UniUserDTO {
    return UniUserDTOFromJSONTyped(json, false);
}

export function UniUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UniUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function UniUserDTOToJSON(json: any): UniUserDTO {
    return UniUserDTOToJSONTyped(json, false);
}

export function UniUserDTOToJSONTyped(value?: UniUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'role': value['role'],
    };
}

